### ISSUE TITLE
The author seems to be a gaylord

### ISSUE THREAD

**Issue by alongoldboimm** [yigaldviri/yaefes#3]
![screen shot 2018-05-16 at 1 56 36 pm](https://user-images.githubusercontent.com/32428873/42420281-fb165ce0-82cb-11e8-8d1b-b19d33ae6780.png)

**Comment by yigal-simplex** [comment]
Not you.

<img width="476" alt="screen shot 2018-07-08 at 16 57 11" src="https://user-images.githubusercontent.com/30213730/42420549-00a8237e-82d0-11e8-810f-e3dc5f2031a6.png">
